# Generated by Django 3.2.9 on 2021-11-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('id_auto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_retiro', models.CharField(max_length=20)),
                ('ubicacion_retorno', models.CharField(max_length=20)),
                ('conductor', models.CharField(max_length=20)),
                ('preferencia_aire_acondicionado', models.BooleanField()),
                ('pago_electronico', models.BooleanField()),
                ('id_viaje', models.IntegerField()),
            ],
        ),
    ]
