# Generated by Django 3.2.9 on 2021-12-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrada', '0007_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(upload_to='avatares'),
        ),
    ]
