# Generated by Django 3.2.9 on 2021-12-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrada', '0008_auto_20211215_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
