# Generated by Django 3.2.9 on 2021-12-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrada', '0009_auto_20211215_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatares'),
            preserve_default=False,
        ),
    ]
